`numpy` - computations on numerical data

In [18]:
kanto=[73,67,43]
jahto =[91,88,64]
hoenn = [87,134,58]
sinnoh = [102,96,70]

w1,w2,w3 = 0.3,0.2,0.5

weights = [w1,w2,w3]

here, 
crop_yield = w1 X rainfall + w2 x humidity + w3 x temp

zip -> zip returns pairs out of the two lists

In [12]:
for x,w in zip(kanto,weights):
    
    print(x)
    print(w)
    print("x*w :"+str(x*w))
    

73
0.3
x*w :21.9
67
0.2
x*w :13.4
43
0.5
x*w :21.5


In [13]:
def crop_yield(region,weights):
    result=0
    for x,w in zip(region,weights):
        result+=x*w
        print(result)


In [15]:
crop_yield(kanto,weights)

21.9
35.3
56.8


In [17]:
crop_yield(sinnoh, weights)

30.599999999999998
49.8
84.8


In [20]:
import numpy as np

In [21]:
kanto = np.array([73,56,43])
# all elements in np arrays have the same datatype

In [22]:
kanto

array([73, 56, 43])

In [23]:
type(kanto)

numpy.ndarray

In [24]:
weights = np.array([w1,w2,w3])

In [25]:
type(weights)

numpy.ndarray

In [26]:
weights[2]

0.5

#### dot product

In [27]:
np.dot(kanto,weights)

54.6

In [28]:
## you can also do it as
(kanto*weights).sum()

54.6

In [33]:
# does element-wise multiplication
kanto*weights

array([21.9, 11.2, 21.5])

In [34]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])
arr1 * arr2

array([ 2,  6, 12])

In [36]:
(arr1 * arr2).sum()

20

In [37]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "prabhat-himika/numerical-computing-with-numpy" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/prabhat-himika/numerical-computing-with-numpy


'https://jovian.com/prabhat-himika/numerical-computing-with-numpy'

#### Benefits of using numpy arrays 
- ease of use and performance(internally implemented in c++)

### Multidimensional arrays

In [45]:
# 2D array - in np library
climate_data = np.array ( [  
        [1,2,3],
        [2,3,4]
    ])
 
climate_data

array([[1, 2, 3],
       [2, 3, 4]])

In [46]:
climate_data.shape ## an attribute of np arrays


(2, 3)

In [47]:
# 3D array
array_3d = np.array([
    [
        [1,2,3],
        [2,3,4]
    ],
    [
        [4,5,6],
        [6,7,8]
    ]
])

In [48]:
array_3d.shape

(2, 2, 3)

In [50]:
array_3d.dtype # dtype = data type eg - int64, float64

dtype('int64')

#### matrix multiplication

1. np.matmul(arr1,arr2)
2. arr1 @ arr2


In [51]:
kanto @ weights

54.6

In [54]:
np.matmul(arr1,arr2)

20

### Working with CSV files

urllib.request - offers url related utilities - making requests, downloading files, url retrieve

urllib.request.urlretrieve(url , path where you want to save it)

`np.genfromtxt`( filename, delimiter, skip_header =1/0)

`np.concatenate`((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

- a1,a2..must be of the same shape except the dimension corresponding to the axis 

`np.reshape` - gives a new shape to an array without changing its data

`np.savetxt` - save an array to a text file
savetxt(filename you want to save it in, arr, fmt='%.18e', delimiter=' ', newline='\n', header='heading1,heading2,...', footer='', comments='', encoding=None)

fmt - formating string - 0.2f -> only 2 decimal points

`Other functions`:

Numpy provides hundreds of functions for performing operations on arrays. Here are some commonly used functions:

- Mathematics: np.sum, np.exp, np.round, arithemtic operators

- Array manipulation: np.reshape, np.stack, np.concatenate, np.split

- Linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals

- Statistics: np.mean, np.median, np.std, np.max


In [56]:
import urllib.request
urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f126e07f760>)

In [58]:
# load the csv file as numpy array using np.genfromtxt( filename, delimiter, skip_header =1/0)
climate_data = np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [59]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [60]:
climate_data.shape

(10000, 3)

In [61]:
yields = climate_data@weights

In [62]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [63]:
yields.shape

(10000,)

In [77]:
c_results = np.concatenate((climate_data,yields.reshape(10000,1)),axis =1)

In [78]:
c_results

array([[25. , 76. , 99. , 67.4],
       [39. , 65. , 70. , 55.3],
       [59. , 45. , 77. , 56.1],
       ...,
       [99. , 62. , 58. , 61.6],
       [70. , 71. , 91. , 71.7],
       [92. , 39. , 76. , 60.5]])

In [87]:
np.savetxt("climate_results.txt",c_results,fmt='%0.2f', header='temp,rainfall,humidity,yields',comments='# this is a comment\n')

In [101]:
# two check for the number of similar elements in two arrays

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,7]])

In [99]:
arr1 == arr2


array([[ True,  True,  True],
       [ True,  True, False]])

In [104]:
type((arr1 ==arr2).sum())
# true =1, false = 0

numpy.int64

In [103]:
arr1<=arr2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [105]:
arr3 = np.array([[ True,  True,  True],
       [ True,  True,  True]])

In [106]:
arr4 = np.array([[ False,  True,  True],
       [ True,  True,  True]])

In [107]:
arr3 == arr4

array([[False,  True,  True],
       [ True,  True,  True]])

In [111]:
arr3 >arr4 

array([[ True, False, False],
       [False, False, False]])

#### Array indexing and slicing

In [112]:
arrn = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [113]:
arrn.shape

(3, 2, 4)

In [114]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "prabhat-himika/numerical-computing-with-numpy" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/prabhat-himika/numerical-computing-with-numpy


'https://jovian.com/prabhat-himika/numerical-computing-with-numpy'